/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/home/index" |
       "/pages/login/index" |
       "/pages/search/index" |
       "/pages/search/searchAppoint" |
       "/pages/task/index" |
       "/pages/waybill/index" |
       "/pages-sub/login/forgetpass" |
       "/pages-sub/login/loginForm" |
       "/pages-sub/login/verifyLogin";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/task/index" | "/pages/waybill/index" | "/pages/home/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
